spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/molorane/config-seal.git #tells spring where to locate the config files
          cloneOnStart: true
  security:
    user:
      password: 1234 #the password which apps will use to access its configurations
  application:
    name: seal-config-service

server:
  port: 7777 #the port where the config-server will be accessible
